// frontend/src/features/dashboard/ChangesChart.tsx
import { useMemo } from 'react'
import { barY, defineChart, stack } from '@tanstack/charts'
import { crosshair } from '@tanstack/charts/crosshair'
import { Chart } from '@tanstack/charts/react'
import { scaleBand } from '@tanstack/charts/scales/band'
import { scaleLinear } from '@tanstack/charts/scales/linear'
import { tooltip } from '@tanstack/charts/tooltip'
import { __ } from '@common/helpers/i18nWrap'
import { palette } from '@config/theme'
import { type DashboardRange, RANGES, periodLabel, useRangeStats } from './dashboardRange'
import type { FindingStats, Severity } from '@/api/types'

const HEIGHT = 200
const MAX_COLUMN = 24

/*
 * Stack order is deliberate: blue between amber and red. As adjacent marks the
 * status red and amber fail colorblind separation (deutan dE 2.1), so they must
 * never touch; with info between them every adjacent pair validates.
 */
const STACK: Severity[] = ['warning', 'info', 'critical']

/** Display order for the legend, tooltip and aria text; STACK orders the marks. */
export const CHART_SEVERITIES: { key: Severity; label: string; tone: string }[] = [
  { key: 'critical', label: __('Critical'), tone: 'var(--scm-viz-critical)' },
  { key: 'warning', label: __('Warning'), tone: 'var(--scm-viz-warning)' },
  { key: 'info', label: __('Info'), tone: 'var(--scm-viz-info)' }
]

const BY_KEY = new Map(CHART_SEVERITIES.map(s => [s.key, s]))

/** Up to 1, 2, 3, 4, 5, 6 or 8 × 10^n, so the midline tick stays a round number. */
const roundUpNice = (value: number) => {
  const magnitude = 10 ** Math.floor(Math.log10(value))

  return [1, 2, 3, 4, 5, 6, 8, 10].find(step => step * magnitude >= value)! * magnitude
}

/** One row per period and severity, zeros included, so every period can take focus. */
interface PeriodCount {
  period: string
  severity: Severity
  count: number
}

function countByPeriod(stats: FindingStats['periods'], periods: string[]): PeriodCount[] {
  const counts = new Map(periods.map(period => [period, { critical: 0, warning: 0, info: 0 }]))

  for (const { period, severity, count } of stats) {
    const bucket = counts.get(period)
    if (bucket && severity in bucket) bucket[severity] += count
  }

  return periods.flatMap(period =>
    STACK.map(severity => ({ period, severity, count: counts.get(period)![severity] }))
  )
}

export default function ChangesChart({ range }: { range: DashboardRange }) {
  const { periods, data } = useRangeStats(range)
  const { labelEvery, empty, changesTitle } = RANGES[range]

  const rows = useMemo(() => countByPeriod(data?.periods ?? [], periods), [data, periods])
  const grandTotal = rows.reduce((sum, row) => sum + row.count, 0)

  const definition = useMemo(() => {
    const totals = periods.map(period =>
      rows.filter(row => row.period === period).reduce((sum, row) => sum + row.count, 0)
    )
    const yMax = 2 * roundUpNice(Math.max(...totals, 4) / 2)
    // Anchor labels to the newest period and step back evenly, so the right
    // edge never carries two labels side by side.
    const labelled = periods.filter((_, i) => (periods.length - 1 - i) % labelEvery === 0)

    return defineChart({
      marks: [
        // Before the bars, so the hover band sits underneath them.
        crosshair({
          x: { band: { fill: 'var(--scm-line-soft)', fillOpacity: 0.6 } },
          y: false
        }),
        barY(rows, {
          x: 'period',
          y: 'count',
          z: 'severity',
          color: 'severity',
          layout: stack({ order: STACK }),
          maxThickness: MAX_COLUMN,
          radius: { end: 4 },
          // A surface-coloured edge opens the 2px gap between stacked segments.
          stroke: row => (row.count > 0 ? 'var(--scm-surface)' : 'none'),
          strokeWidth: 2
        })
      ],
      scales: {
        // Configured instances, not factories: a factory's domain is re-inferred
        // from the data, which collapses the axis when every count is zero.
        x: {
          scale: scaleBand<string>().domain(periods).padding(0.45),
          axis: {
            line: false,
            ticks: { values: labelled, size: 0, format: period => periodLabel(period) },
            tickLabels: { fontSize: 11 }
          }
        },
        y: {
          scale: scaleLinear().domain([0, yMax]),
          grid: { stroke: 'var(--scm-line-soft)', strokeOpacity: 1 },
          axis: {
            line: false,
            ticks: { values: [0, yMax / 2, yMax], size: 0, format: String },
            tickLabels: { fontSize: 11 }
          }
        }
      },
      color: {
        domain: STACK,
        range: STACK.map(severity => BY_KEY.get(severity)!.tone)
      },
      theme: {
        foreground: 'var(--scm-ink)',
        muted: 'var(--scm-ink-muted)'
      },

      // The whole day is the hover target, not just the painted column.
      focus: 'group-x',
      maxFocusDistance: Number.POSITIVE_INFINITY,
      focusRing: false,
      tooltip: {
        use: tooltip,
        className: 'scm-chart-tooltip',
        anchor: { x: 'value', y: 'plot-top' },
        placement: 'bottom',
        content: points => {
          const period = points[0]?.datum.period ?? ''
          const counts = new Map(points.map(point => [point.datum.severity, point.datum.count]))

          return {
            title: periodLabel(period, true),
            rows: CHART_SEVERITIES.map(({ key, label, tone }) => ({
              label,
              value: String(counts.get(key) ?? 0),
              color: tone
            }))
          }
        }
      }
    })
  }, [rows, periods, labelEvery])

  return (
    <div className="relative">
      {grandTotal === 0 && data && (
        <p
          className="absolute inset-0 z-10 m-0 flex items-center justify-center pb-4 text-xs"
          style={{ color: palette.inkMuted }}
        >
          {empty}
        </p>
      )}

      <Chart
        ariaLabel={changesTitle}
        definition={definition}
        height={HEIGHT}
      />
    </div>
  )
}

// frontend/src/features/dashboard/ChangesChart.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { __ } from '@common/helpers/i18nWrap'
import { useFindings } from '@/api/queries'
import { palette } from '@config/theme'
import { WINDOW_DAYS as DAYS, recentDays } from './recentWindow'
import { CHART_SEVERITIES, SEVERITY_BY_KEY, STACK_ORDER as STACK } from './severities'
import type { Finding, Severity } from '@/api/types'

const HEIGHT = 200
const MARGIN = { top: 8, right: 8, bottom: 22, left: 30 }
const MAX_COLUMN = 24
const SEGMENT_GAP = 2

const dayLabel = (iso: string) =>
  new Date(`${iso}T00:00:00Z`).toLocaleDateString(undefined, {
    day: 'numeric',
    month: 'short',
    timeZone: 'UTC'
  })

type DayBucket = { day: string } & Record<Severity, number>

function bucketByDay(items: Finding[], days: string[]): DayBucket[] {
  const buckets = new Map<string, DayBucket>(
    days.map(day => [day, { day, critical: 0, warning: 0, info: 0 }])
  )

  for (const finding of items) {
    const bucket = buckets.get((finding.created_at ?? '').slice(0, 10))
    if (bucket) bucket[finding.severity] += 1
  }

  return days.map(day => buckets.get(day)!)
}

/** Top segment gets the 4px rounded data-end; the baseline stays square. */
const roundedTopRect = (x: number, y: number, w: number, h: number, r: number) => {
  const radius = Math.min(r, h, w / 2)

  return `M${x},${y + h} V${y + radius} Q${x},${y} ${x + radius},${y} H${x + w - radius} Q${x + w},${y} ${x + w},${y + radius} V${y + h} Z`
}

const days = recentDays()
const { data } = useFindings({ date_from: days[0], per_page: 100 })

const wrap = ref<HTMLElement | null>(null)
const width = ref(0)
const hovered = ref<number | null>(null)

let observer: ResizeObserver | null = null

watch(
  wrap,
  el => {
    observer?.disconnect()
    if (!el) return

    observer = new ResizeObserver(entries => {
      width.value = entries[0].contentRect.width
    })
    observer.observe(el)
  },
  { flush: 'post', immediate: true }
)

onUnmounted(() => observer?.disconnect())

const buckets = computed(() => bucketByDay(data.value?.items ?? [], days))
const totals = computed(() => buckets.value.map(b => b.critical + b.warning + b.info))
const grandTotal = computed(() => totals.value.reduce((sum, n) => sum + n, 0))
const yMax = computed(() => Math.ceil(Math.max(...totals.value, 4) / 2) * 2)
const ticks = computed(() => [0, yMax.value / 2, yMax.value])

const innerW = computed(() => Math.max(width.value - MARGIN.left - MARGIN.right, 0))
const innerH = HEIGHT - MARGIN.top - MARGIN.bottom
const band = computed(() => innerW.value / DAYS)
const column = computed(() => Math.min(MAX_COLUMN, band.value * 0.55))

const yOf = (value: number) => MARGIN.top + innerH - (value / yMax.value) * innerH

/** Segment geometry per day, so the template never mutates state while rendering. */
const columns = computed(() =>
  buckets.value.map((bucket, i) => {
    const xBand = MARGIN.left + i * band.value
    const x = xBand + (band.value - column.value) / 2
    // Non-zero counts keep a 2px floor so a single change stays visible.
    const heights = STACK.map(s =>
      bucket[s] === 0 ? 0 : Math.max((bucket[s] / yMax.value) * innerH, 2)
    )

    let y = yOf(0)
    const segments = STACK.flatMap((severity, s) => {
      const h = heights[s]
      if (h === 0) return []

      y -= h
      const top = y
      const isTopmost = heights.slice(s + 1).every(rest => rest === 0)
      y -= SEGMENT_GAP

      return [
        {
          height: h,
          isTopmost,
          path: isTopmost ? roundedTopRect(x, top, column.value, h, 4) : '',
          severity,
          tone: SEVERITY_BY_KEY.get(severity)!.tone,
          y: top
        }
      ]
    })

    return {
      aria: `${dayLabel(bucket.day)}: ${CHART_SEVERITIES.map(
        ({ key, label }) => `${bucket[key]} ${label}`
      ).join(', ')}`,
      bucket,
      // Anchor labels to the newest day and step back evenly, so the right
      // edge never carries two labels side by side.
      showLabel: (DAYS - 1 - i) % 3 === 0,
      label: dayLabel(bucket.day),
      segments,
      x,
      xBand
    }
  })
)

const hoveredColumn = computed(() =>
  hovered.value === null ? null : (columns.value[hovered.value] ?? null)
)

const tooltipLeft = computed(() => {
  if (hovered.value === null) return 0

  return Math.min(
    Math.max(MARGIN.left + (hovered.value + 0.5) * band.value - 60, 0),
    Math.max(width.value - 130, 0)
  )
})
</script>

<template>
  <div ref="wrap" class="relative">
    <p
      v-if="grandTotal === 0 && data"
      class="absolute inset-0 z-10 m-0 flex items-center justify-center pb-4 text-xs"
      :style="{ color: palette.inkMuted }"
    >
      {{ __('No changes recorded in the last 14 days.') }}
    </p>

    <svg
      v-if="width > 0"
      :aria-label="__('Changes per day by severity, last 14 days')"
      :height="HEIGHT"
      role="img"
      :width="width"
      @mouseleave="hovered = null"
    >
      <g v-for="tick in ticks" :key="tick">
        <line
          stroke="var(--scm-line-soft)"
          :stroke-width="1"
          :x1="MARGIN.left"
          :x2="width - MARGIN.right"
          :y1="yOf(tick)"
          :y2="yOf(tick)"
        />
        <text
          class="tabular-nums"
          fill="var(--scm-ink-muted)"
          :font-size="11"
          text-anchor="end"
          :x="MARGIN.left - 8"
          :y="yOf(tick) + 4"
        >
          {{ tick }}
        </text>
      </g>

      <g v-for="(col, i) in columns" :key="col.bucket.day">
        <rect
          v-if="hovered === i"
          fill="var(--scm-line-soft)"
          :height="innerH"
          :opacity="0.6"
          :width="band"
          :x="col.xBand"
          :y="MARGIN.top"
        />

        <template v-for="segment in col.segments" :key="segment.severity">
          <path v-if="segment.isTopmost" :d="segment.path" :fill="segment.tone" />
          <rect
            v-else
            :fill="segment.tone"
            :height="segment.height"
            :width="column"
            :x="col.x"
            :y="segment.y"
          />
        </template>

        <text
          v-if="col.showLabel"
          fill="var(--scm-ink-muted)"
          :font-size="11"
          text-anchor="middle"
          :x="col.xBand + band / 2"
          :y="HEIGHT - 6"
        >
          {{ col.label }}
        </text>

        <!-- Hit target: the whole day band, not just the painted column. -->
        <rect
          :aria-label="col.aria"
          fill="transparent"
          :height="innerH"
          :tabindex="0"
          :width="band"
          :x="col.xBand"
          :y="MARGIN.top"
          @blur="hovered = null"
          @focus="hovered = i"
          @mouseenter="hovered = i"
        />
      </g>
    </svg>

    <div
      v-if="hoveredColumn"
      class="pointer-events-none absolute z-20 rounded-md border border-solid px-3 py-2 shadow-sm"
      :style="{
        background: palette.surface,
        borderColor: palette.line,
        left: `${tooltipLeft}px`,
        top: 0
      }"
    >
      <p class="m-0 mb-1 text-xs font-medium" :style="{ color: palette.ink }">
        {{ hoveredColumn.label }}
      </p>
      <p
        v-for="severity in CHART_SEVERITIES"
        :key="severity.key"
        class="m-0 flex items-center gap-2 text-xs"
      >
        <span class="h-2.5 w-1 rounded-sm" :style="{ background: severity.tone }" />
        <span class="font-semibold tabular-nums" :style="{ color: palette.ink }">
          {{ hoveredColumn.bucket[severity.key] }}
        </span>
        <span :style="{ color: palette.inkMuted }">{{ severity.label }}</span>
      </p>
    </div>
  </div>
</template>
