// frontend/src/features/dashboard/DashboardPage.vue
<script setup lang="ts">
import {
  CheckCircleFilled,
  ReloadOutlined,
  RightOutlined,
  SafetyCertificateOutlined
} from '@ant-design/icons-vue'
import { Alert, Button, Card, Popconfirm, message } from 'ant-design-vue'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { __, sprintf } from '@common/helpers/i18nWrap'
import {
  useArmBaseline,
  useCheckNow,
  useDashboardSummary,
  useDisarmBaseline,
  useFindings,
  useRunStatus
} from '@/api/queries'
import { changeLabel, eventLabel } from '@components/changeLabels'
import PageHeader from '@components/PageHeader.vue'
import SeverityStrip from '@components/SeverityStrip.vue'
import When from '@components/When.vue'
import { palette } from '@config/theme'
import { useFlightLogStore } from '@/store/flightLogStore'
import ChangesChart from './ChangesChart.vue'
import CrawlerActivity from './CrawlerActivity.vue'
import StatusRow from './StatusRow.vue'
import TypeBreakdown from './TypeBreakdown.vue'
import { CHART_SEVERITIES } from './severities'
import type { Severity } from '@/api/types'

const SEVERITY_TONE: Record<Severity, string> = {
  critical: palette.critical,
  info: palette.info,
  warning: palette.warning
}

const router = useRouter()
const flightLog = useFlightLogStore()

const { data: summary } = useDashboardSummary()
const { data: run } = useRunStatus()
// Only the short "needs attention" list; the strip uses server-side counts so
// it stays correct past one page of findings.
const { data: recent } = useFindings({ status: ['open'], per_page: 6 })

const checkNow = useCheckNow()
const armBaseline = useArmBaseline()
const disarmBaseline = useDisarmBaseline()

const counts = computed(() => summary.value?.open_counts ?? { critical: 0, warning: 0, info: 0 })
const items = computed(() => recent.value?.items ?? [])
const events = computed(() => (summary.value?.recent_events ?? []).slice(0, 5))
const isRunning = computed(() => run.value?.status === 'running' || checkNow.isPending.value)
const isImpaired = computed(
  () => Boolean(summary.value?.impaired) || run.value?.status === 'impaired'
)

const openSeverity = (severity: Severity) => {
  flightLog.showOnly([severity])
  router.push('/log')
}

const runCheck = () =>
  checkNow.mutate(undefined, {
    onSuccess: () => message.success(__('Check complete.')),
    onError: error => message.error(error.message)
  })

const arm = () =>
  armBaseline.mutate(undefined, {
    onSuccess: data =>
      message.success(
        sprintf(
          __('Baseline saved for %d pages. Run your updates, then check again.'),
          data.targets
        )
      ),
    onError: error => message.error(error.message)
  })
</script>

<template>
  <PageHeader :title="__('Dashboard')">
    <template #actions>
      <Popconfirm
        v-if="summary?.baseline"
        :cancel-text="__('Keep it')"
        :ok-text="__('Discard')"
        :title="__('Discard the saved baseline?')"
        @confirm="disarmBaseline.mutate()"
      >
        <Button :loading="disarmBaseline.isPending.value">{{ __('Discard baseline') }}</Button>
      </Popconfirm>
      <Button v-else :loading="armBaseline.isPending.value" @click="arm">
        <template #icon><SafetyCertificateOutlined /></template>
        {{ __('Arm baseline') }}
      </Button>

      <Button :loading="isRunning" type="primary" @click="runCheck">
        <template #icon><ReloadOutlined /></template>
        {{ __('Check now') }}
      </Button>
    </template>
  </PageHeader>

  <!--
    Spacing lives on this column: margin utilities on antd roots lose to its
    cssinjs reset at high hash priority.
  -->
  <div class="flex flex-col gap-4">
    <Alert
      v-if="isImpaired"
      show-icon
      :description="
        summary?.impaired?.reason ??
        __('This plugin could not fetch your pages on the last run, so no all-clear can be given.')
      "
      :message="__('Monitoring impaired')"
      type="warning"
    />

    <Alert
      v-if="summary?.baseline"
      show-icon
      :description="
        __(
          'The next check compares against this snapshot instead of the last run, so anything your updates break shows up clearly. It expires on its own after 24 hours.'
        )
      "
      :message="__('Baseline saved. Go ahead and run your updates')"
      type="info"
    />

    <div class="grid grid-cols-1 items-start gap-4 lg:grid-cols-5">
      <div class="flex flex-col gap-4 lg:col-span-3">
        <SeverityStrip :counts="counts" @select="openSeverity" />

        <Card :title="__('Changes over the last 14 days')">
          <template #extra>
            <div class="flex items-center gap-4">
              <span
                v-for="severity in CHART_SEVERITIES"
                :key="severity.key"
                class="flex items-center gap-1.5 text-xs"
                :style="{ color: palette.inkMuted }"
              >
                <span class="h-2.5 w-2.5 rounded-sm" :style="{ background: severity.tone }" />
                {{ severity.label }}
              </span>
            </div>
          </template>
          <ChangesChart />
        </Card>

        <Card :title="__('Needs your attention')">
          <template v-if="items.length > 0" #extra>
            <Button size="small" type="link" @click="router.push('/log')">
              {{ __('View all') }}
            </Button>
          </template>

          <div
            v-if="items.length === 0"
            class="flex flex-col items-center gap-1 px-4 py-10 text-center"
          >
            <CheckCircleFilled :style="{ color: palette.success, fontSize: '22px' }" />
            <p class="m-0 mt-2 text-sm font-medium" :style="{ color: palette.ink }">
              {{ __('Nothing unexpected has changed.') }}
            </p>
            <p class="m-0 max-w-xs text-xs" :style="{ color: palette.inkMuted }">
              {{ __('We will tell you the moment something does.') }}
            </p>
          </div>

          <!--
            Rows are full-bleed against the card padding so the hover band and
            the dividers reach its edges the way a table's would.
          -->
          <ul v-else class="-mx-4 -my-2 flex list-none flex-col p-0">
            <li v-for="(finding, i) in items" :key="finding.id">
              <button
                :class="[
                  'scm-hover group flex w-full cursor-pointer items-center gap-3 border-0 border-solid bg-transparent px-4 py-2.5 text-left transition-colors',
                  { 'border-t': i > 0 }
                ]"
                :style="{ borderColor: palette.lineSoft }"
                type="button"
                @click="router.push('/log')"
              >
                <span
                  class="h-1.5 w-1.5 shrink-0 rounded-full"
                  :style="{ background: SEVERITY_TONE[finding.severity] }"
                />
                <span class="min-w-0 flex-1">
                  <span class="block truncate text-sm font-medium" :style="{ color: palette.ink }">
                    {{ changeLabel(finding.change_type) }}
                  </span>
                  <span class="block truncate text-xs" :style="{ color: palette.inkMuted }">
                    {{ finding.target_label ?? finding.target_url ?? __('Site-wide') }}
                  </span>
                </span>
                <When class-name="hidden shrink-0 sm:block" :value="finding.created_at" />
                <RightOutlined
                  class="shrink-0 text-xs opacity-0 transition-opacity group-hover:opacity-100"
                  :style="{ color: palette.inkFaint }"
                />
              </button>
            </li>
          </ul>
        </Card>
      </div>

      <div class="flex flex-col gap-4 lg:col-span-2">
        <Card :title="__('Monitoring status')">
          <dl class="m-0 flex flex-col gap-2.5 text-sm">
            <StatusRow :label="__('Pages monitored')">
              {{ summary?.active_targets ?? 0 }}
            </StatusRow>
            <StatusRow :label="__('Last check')">
              <When :fallback="__('never')" :value="summary?.last_run?.finished_at" />
            </StatusRow>
            <StatusRow :label="__('Next check')">
              <span v-if="summary?.frequency === 'off'">{{ __('scheduling is off') }}</span>
              <When v-else :fallback="__('not scheduled')" :value="summary?.next_run_at" />
            </StatusRow>
            <StatusRow :label="__('Last run')" :tone="isImpaired ? palette.warning : undefined">
              {{ summary?.last_run?.status ?? __('never run') }}
            </StatusRow>
          </dl>
        </Card>

        <Card :title="__('Change types · last 14 days')">
          <TypeBreakdown />
        </Card>

        <Card :title="__('AI crawler visits')">
          <CrawlerActivity />
        </Card>

        <Card :title="__('Recent site activity')">
          <p
            v-if="events.length === 0"
            class="m-0 py-2 text-xs"
            :style="{ color: palette.inkMuted }"
          >
            {{ __('Nothing has changed on this site lately.') }}
          </p>
          <ul v-else class="m-0 flex list-none flex-col gap-2.5 p-0">
            <li v-for="event in events" :key="event.id" class="flex items-baseline gap-2.5 text-sm">
              <span
                class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full"
                :style="{ background: palette.inkFaint }"
              />
              <span class="min-w-0 flex-1">
                <span class="font-medium" :style="{ color: palette.ink }">
                  {{ eventLabel(event.type) }}
                </span>
                <!-- Explicit space: a Vue template collapses the newline between
                     these spans, unlike the JSX {' '} it replaced. -->
                {{ ' ' }}
                <span class="break-words text-xs" :style="{ color: palette.inkMuted }">
                  {{ event.subject }}
                </span>
              </span>
              <When class-name="shrink-0" :value="event.at" />
            </li>
          </ul>
        </Card>
      </div>
    </div>
  </div>
</template>

// frontend/src/features/dashboard/DashboardPage.tsx
import {
  CheckCircleFilled,
  ReloadOutlined,
  RightOutlined,
  SafetyCertificateOutlined
} from '@ant-design/icons'
import { Alert, App, Button, Card, Popconfirm, Tooltip } from 'antd'
import { useNavigate } from 'react-router'
import classNames from '@common/helpers/classNames'
import { __, sprintf } from '@common/helpers/i18nWrap'
import {
  useArmBaseline,
  useCheckNow,
  useDashboardSummary,
  useDisarmBaseline,
  useFindings,
  useRunStatus
} from '@/api/queries'
import { changeLabel, eventLabel } from '@components/changeLabels'
import PageHeader from '@components/PageHeader'
import SeverityStrip from '@components/SeverityStrip'
import ChangesChart, { CHART_SEVERITIES } from './ChangesChart'
import CrawlerActivity from './CrawlerActivity'
import TypeBreakdown from './TypeBreakdown'
import When from '@components/When'
import { palette } from '@config/theme'
import { useFlightLogStore } from '@/store/flightLogStore'
import type { Severity } from '@/api/types'
import type { ReactNode } from 'react'

const SEVERITY_TONE: Record<Severity, string> = {
  critical: palette.critical,
  info: palette.info,
  warning: palette.warning
}

export default function DashboardPage() {
  const navigate = useNavigate()
  const { message } = App.useApp()
  const showOnly = useFlightLogStore(state => state.showOnly)

  const { data: summary } = useDashboardSummary()
  const { data: run } = useRunStatus()
  // Only the short "needs attention" list; the strip uses server-side counts so
  // it stays correct past one page of findings.
  const { data: recent } = useFindings({ status: ['open'], per_page: 6 })

  const checkNow = useCheckNow()
  const armBaseline = useArmBaseline()
  const disarmBaseline = useDisarmBaseline()

  const counts = summary?.open_counts ?? { critical: 0, warning: 0, info: 0 }
  const items = recent?.items ?? []
  const events = summary?.recent_events ?? []
  const isRunning = run?.status === 'running' || checkNow.isPending
  const isImpaired = Boolean(summary?.impaired) || run?.status === 'impaired'

  const openSeverity = (severity: Severity) => {
    showOnly([severity])
    navigate('/log')
  }

  const runCheck = () => {
    checkNow.mutate(undefined, {
      onSuccess: () => message.success(__('Check complete.')),
      onError: error => message.error(error.message)
    })
  }

  const arm = () => {
    armBaseline.mutate(undefined, {
      onSuccess: data =>
        message.success(
          sprintf(
            __('Snapshot saved for %d pages. Run your updates, then check again.'),
            data.targets
          )
        ),
      onError: error => message.error(error.message)
    })
  }

  return (
    <>
      <PageHeader
        actions={
          <>
            {summary?.baseline ? (
              <Popconfirm
                cancelText={__('Keep it')}
                okText={__('Discard')}
                title={__('Discard the saved snapshot?')}
                onConfirm={() => disarmBaseline.mutate()}
              >
                <Button loading={disarmBaseline.isPending}>{__('Discard snapshot')}</Button>
              </Popconfirm>
            ) : (
              <Tooltip
                title={__(
                  'Takes a snapshot of every monitored page right now. Use this just before a theme, plugin or content update: the next check compares against this snapshot instead of the last one, so you see exactly what the update changed. It expires on its own after 24 hours.'
                )}
              >
                <Button
                  icon={<SafetyCertificateOutlined />}
                  loading={armBaseline.isPending}
                  onClick={arm}
                >
                  {__('Snapshot now')}
                </Button>
              </Tooltip>
            )}
            <Tooltip title={__('Runs every check immediately, instead of waiting for the next scheduled run.')}>
              <Button icon={<ReloadOutlined />} loading={isRunning} type="primary" onClick={runCheck}>
                {__('Check now')}
              </Button>
            </Tooltip>
          </>
        }
        title={__('Dashboard')}
      />

      {/* Spacing lives on this column: margin utilities on antd roots lose to
          its cssinjs reset at high hash priority. */}
      <div className="flex flex-col gap-4">
        {isImpaired && (
          <Alert
            showIcon
            description={
              summary?.impaired?.reason ??
              __(
                'This plugin could not fetch your pages on the last run, so no all-clear can be given.'
              )
            }
            message={__('Monitoring impaired')}
            type="warning"
          />
        )}

        {summary?.baseline && (
          <Alert
            showIcon
            description={__(
              'The next check compares against this snapshot instead of the last run, so anything your updates break shows up clearly. It expires on its own after 24 hours.'
            )}
            message={__('Snapshot saved. Go ahead and run your updates')}
            type="info"
          />
        )}

        <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-5">
          <div className="flex flex-col gap-4 lg:col-span-3">
            <SeverityStrip counts={counts} onSelect={openSeverity} />
            <Card
              extra={
                <div className="flex items-center gap-4">
                  {CHART_SEVERITIES.map(({ label, tone }) => (
                    <span
                      key={label}
                      className="flex items-center gap-1.5 text-xs"
                      style={{ color: palette.inkMuted }}
                    >
                      <span className="h-2.5 w-2.5 rounded-sm" style={{ background: tone }} />
                      {label}
                    </span>
                  ))}
                </div>
              }
              title={__('Changes over the last 14 days')}
            >
              <ChangesChart />
            </Card>

            <Card
              extra={
                items.length > 0 ? (
                  <Button size="small" type="link" onClick={() => navigate('/log')}>
                    {__('View all')}
                  </Button>
                ) : null
              }
              title={__('Needs your attention')}
            >
              {items.length === 0 ? (
                <div className="flex flex-col items-center gap-1 px-4 py-10 text-center">
                  <CheckCircleFilled style={{ color: palette.success, fontSize: 22 }} />
                  <p className="m-0 mt-2 text-sm font-medium" style={{ color: palette.ink }}>
                    {__('Nothing unexpected has changed.')}
                  </p>
                  <p className="m-0 max-w-xs text-xs" style={{ color: palette.inkMuted }}>
                    {__('We will tell you the moment something does.')}
                  </p>
                </div>
              ) : (
                // Rows are full-bleed against the card padding so the hover band
                // and the dividers reach its edges the way a table's would.
                <ul className="-mx-4 -my-2 flex list-none flex-col p-0">
                  {items.map((finding, index) => (
                    <li key={finding.id}>
                      <button
                        className={classNames(
                          'scm-hover group flex w-full cursor-pointer items-center gap-3 border-0 border-solid bg-transparent px-4 py-2.5 text-left transition-colors',
                          index > 0 && 'border-t'
                        )}
                        style={{ borderColor: palette.lineSoft }}
                        type="button"
                        onClick={() => navigate('/log')}
                      >
                        <span
                          className="h-1.5 w-1.5 shrink-0 rounded-full"
                          style={{ background: SEVERITY_TONE[finding.severity] }}
                        />
                        <span className="min-w-0 flex-1">
                          <span
                            className="block truncate text-sm font-medium"
                            style={{ color: palette.ink }}
                          >
                            {changeLabel(finding.change_type)}
                          </span>
                          <span
                            className="block truncate text-xs"
                            style={{ color: palette.inkMuted }}
                          >
                            {finding.target_label ?? finding.target_url ?? __('Site-wide')}
                          </span>
                        </span>
                        <When className="hidden shrink-0 sm:block" value={finding.created_at} />
                        <RightOutlined
                          className="shrink-0 text-xs opacity-0 transition-opacity group-hover:opacity-100"
                          style={{ color: palette.inkFaint }}
                        />
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </Card>
          </div>

          <div className="flex flex-col gap-4 lg:col-span-2">
            <Card title={__('Monitoring status')}>
              <dl className="m-0 flex flex-col gap-2.5 text-sm">
                <Row label={__('Pages monitored')} value={String(summary?.active_targets ?? 0)} />
                <Row
                  label={__('Last check')}
                  value={<When fallback={__('never')} value={summary?.last_run?.finished_at} />}
                />
                <Row
                  label={__('Next check')}
                  value={
                    summary?.frequency === 'off' ? (
                      __('scheduling is off')
                    ) : (
                      <When fallback={__('not scheduled')} value={summary?.next_run_at} />
                    )
                  }
                />
                <Row
                  label={__('Last run')}
                  tone={isImpaired ? palette.warning : undefined}
                  value={summary?.last_run?.status ?? __('never run')}
                />
              </dl>
            </Card>

            <Card title={__('Change types · last 14 days')}>
              <TypeBreakdown />
            </Card>

            <Card title={__('AI crawler visits')}>
              <CrawlerActivity />
            </Card>

            <Card title={__('Recent site activity')}>
              {events.length === 0 ? (
                <p className="m-0 py-2 text-xs" style={{ color: palette.inkMuted }}>
                  {__('Nothing has changed on this site lately.')}
                </p>
              ) : (
                <ul className="m-0 flex list-none flex-col gap-2.5 p-0">
                  {events.slice(0, 5).map(event => (
                    <li key={event.id} className="flex items-baseline gap-2.5 text-sm">
                      <span
                        className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full"
                        style={{ background: palette.inkFaint }}
                      />
                      <span className="min-w-0 flex-1">
                        <span className="font-medium" style={{ color: palette.ink }}>
                          {eventLabel(event.type)}
                        </span>{' '}
                        <span className="break-words text-xs" style={{ color: palette.inkMuted }}>
                          {event.subject}
                        </span>
                      </span>
                      <When className="shrink-0" value={event.at} />
                    </li>
                  ))}
                </ul>
              )}
            </Card>
          </div>
        </div>
      </div>
    </>
  )
}

function Row({ label, value, tone }: { label: string; tone?: string; value: ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <dt className="m-0 shrink-0" style={{ color: palette.inkMuted }}>
        {label}
      </dt>
      <dd className="m-0 truncate font-medium" style={{ color: tone ?? palette.ink }}>
        {value}
      </dd>
    </div>
  )
}
