// frontend/src/features/settings/SettingsPage.vue
<script setup lang="ts">
import {
  Button,
  Card,
  Form,
  FormItem,
  Input,
  InputNumber,
  Select,
  Space,
  Switch,
  message
} from 'ant-design-vue'
import { reactive, watch } from 'vue'
import { __ } from '@common/helpers/i18nWrap'
import { usePreviewReport, useSendReport, useSettings, useUpdateSettings } from '@/api/queries'
import PageHeader from '@components/PageHeader.vue'
import { palette } from '@config/theme'
import type { Settings } from '@/api/types'

const { data: settings, isLoading } = useSettings()
const updateSettings = useUpdateSettings()
const sendReport = useSendReport()
const previewReport = usePreviewReport()

/*
 * A reactive draft rather than antd's Form.useForm(): ant-design-vue drives
 * fields with v-model, so the form state is plain reactive data that the
 * loaded settings are copied into once they arrive.
 */
const draft = reactive<Partial<Settings>>({})

watch(settings, loaded => loaded && Object.assign(draft, loaded), { immediate: true })

const FREQUENCY = [
  { label: __('Every hour'), value: 'hourly' },
  { label: __('Twice a day'), value: 'twicedaily' },
  { label: __('Once a day'), value: 'daily' },
  { label: __('Off (only when I click Check now)'), value: 'off' }
]

const THRESHOLD = [
  { label: __('Critical changes only'), value: 'critical' },
  { label: __('Critical and warnings'), value: 'warning' },
  { label: __('Everything, including info'), value: 'info' }
]

const submit = () =>
  updateSettings.mutate(
    { ...draft },
    {
      onSuccess: () => message.success(__('Settings saved.')),
      onError: error => message.error(error.message)
    }
  )

const sendNow = () =>
  sendReport.mutate(undefined, {
    onSuccess: () => message.success(__('Report sent.')),
    onError: error => message.error(error.message)
  })

/** Opens the rendered report in a new tab so the branding can be checked. */
const preview = () =>
  previewReport.mutate(undefined, {
    onSuccess: data => {
      const tab = window.open('', '_blank')
      if (!tab) {
        message.warning(__('Allow pop-ups to see the preview.'))

        return
      }

      tab.document.write(data.html)
      tab.document.close()
    },
    onError: error => message.error(error.message)
  })
</script>

<template>
  <div class="mx-auto max-w-2xl">
    <PageHeader :title="__('Settings')" />

    <!--
      Spacing lives on this container, not on the cards: antd's cssinjs runs at
      high hash priority, so a margin utility on .ant-card loses to its reset.
    -->
    <Form class="flex flex-col gap-4" :disabled="isLoading" layout="vertical">
      <Card :title="__('Checking')">
        <FormItem
          class="mb-5"
          :extra="
            __(
              'Checks also run automatically about 90 seconds after any plugin, theme or core update.'
            )
          "
          :label="__('How often to check')"
        >
          <Select v-model:value="draft.frequency" :options="FREQUENCY" />
        </FormItem>

        <FormItem
          class="mb-0"
          :extra="__('0 keeps everything forever. Unresolved critical findings are never deleted.')"
          :label="__('Keep history for (days)')"
        >
          <InputNumber v-model:value="draft.retention_days" class="w-40" :max="3650" :min="0" />
        </FormItem>
      </Card>

      <Card :title="__('Email alerts')">
        <FormItem class="mb-5" :label="__('Email me about changes')">
          <Switch v-model:checked="draft.email_enabled" />
        </FormItem>

        <FormItem class="mb-5" :label="__('Only email me about')">
          <Select v-model:value="draft.email_threshold" :options="THRESHOLD" />
        </FormItem>

        <FormItem
          class="mb-0"
          :extra="__('Leave empty to use the site admin email.')"
          :label="__('Send to')"
        >
          <Input
            v-model:value="draft.email_recipient"
            :placeholder="__('you@example.com')"
            type="email"
          />
        </FormItem>
      </Card>

      <Card :title="__('Weekly client report')">
        <template #extra>
          <Space>
            <Button
              :disabled="isLoading"
              :loading="previewReport.isPending.value"
              size="small"
              @click="preview"
            >
              {{ __('Preview') }}
            </Button>
            <Button
              :disabled="isLoading"
              :loading="sendReport.isPending.value"
              size="small"
              @click="sendNow"
            >
              {{ __('Send now') }}
            </Button>
          </Space>
        </template>

        <FormItem
          class="mb-5"
          :extra="__('Sent every Monday morning. Your branding, not ours.')"
          :label="__('Email a weekly summary')"
        >
          <Switch v-model:checked="draft.report_enabled" />
        </FormItem>

        <FormItem
          class="mb-5"
          :extra="__('Comma-separated. These addresses receive the report.')"
          :label="__('Send to')"
        >
          <Input
            v-model:value="draft.report_recipients"
            :placeholder="__('client@example.com, you@agency.com')"
          />
        </FormItem>

        <div class="flex gap-3">
          <FormItem class="mb-5 flex-1" :label="__('Your business name')">
            <Input
              v-model:value="draft.report_brand_name"
              :placeholder="__('Shown in place of the plugin name')"
            />
          </FormItem>
          <FormItem class="mb-5 w-32" :label="__('Accent colour')">
            <Input v-model:value="draft.report_brand_color" placeholder="#1d4ed8" />
          </FormItem>
        </div>

        <FormItem class="mb-5" :label="__('Logo URL')">
          <Input v-model:value="draft.report_logo_url" placeholder="https://example.com/logo.png" />
        </FormItem>

        <FormItem
          class="mb-0"
          :extra="__('Replaces the default line at the bottom of the report.')"
          :label="__('Footer text')"
        >
          <Input v-model:value="draft.report_footer" :placeholder="__('Prepared by Your Agency')" />
        </FormItem>
      </Card>

      <Card :title="__('AI crawlers')">
        <FormItem
          class="mb-0"
          :extra="
            __(
              'Notes the date each known AI crawler last visited. Full-page caching can hide some visits.'
            )
          "
          :label="__('Record when AI crawlers visit')"
        >
          <Switch v-model:checked="draft.bot_tracking" />
        </FormItem>
      </Card>

      <div
        class="flex items-center gap-3 rounded-lg border border-solid px-5 py-4"
        :style="{ background: palette.surface, borderColor: palette.line }"
      >
        <Button :loading="updateSettings.isPending.value" type="primary" @click="submit">
          {{ __('Save settings') }}
        </Button>
        <span class="text-xs" :style="{ color: palette.inkMuted }">
          {{ __('Changes take effect on the next check.') }}
        </span>
      </div>
    </Form>
  </div>
</template>

// frontend/src/features/settings/SettingsPage.tsx
import { App, Button, Card, Form, Input, InputNumber, Select, Space, Switch, Tabs, Tooltip } from 'antd'
import { useEffect } from 'react'
import { __ } from '@common/helpers/i18nWrap'
import { usePreviewReport, useSendReport, useSettings, useUpdateSettings } from '@/api/queries'
import PageHeader from '@components/PageHeader'
import config from '@config/config'
import type { Settings } from '@/api/types'

export default function SettingsPage() {
  const [form] = Form.useForm<Settings>()
  const { message } = App.useApp()
  const { data: settings, isLoading } = useSettings()
  const updateSettings = useUpdateSettings()
  const sendReport = useSendReport()
  const previewReport = usePreviewReport()
  const emailEnabled = Form.useWatch('email_enabled', form)
  const isEmailFieldDisabled = isLoading || !emailEnabled

  useEffect(() => {
    if (settings) form.setFieldsValue(settings)
  }, [settings, form])

  const submit = (values: Settings) => {
    updateSettings.mutate(values, {
      onSuccess: () => message.success(__('Settings saved.')),
      onError: error => message.error(error.message)
    })
  }

  const sendNow = () => {
    sendReport.mutate(undefined, {
      onSuccess: () => message.success(__('Report sent.')),
      onError: error => message.error(error.message)
    })
  }

  /** Opens the rendered report in a new tab so the branding can be checked. */
  const preview = () => {
    previewReport.mutate(undefined, {
      onSuccess: data => {
        const tab = window.open('', '_blank')
        if (!tab) {
          message.warning(__('Allow pop-ups to see the preview.'))

          return
        }

        tab.document.write(data.html)
        tab.document.close()
      },
      onError: error => message.error(error.message)
    })
  }

  const tabItems = [
    {
      key: 'checking',
      label: __('Checking'),
      children: (
        <Card>
          <Form.Item
            className="mb-5 max-w-md"
            extra={__(
              'Checks also run automatically about 90 seconds after any plugin, theme or core update.'
            )}
            label={__('How often to check')}
            name="frequency"
          >
            <Select
              options={[
                { label: __('Every hour'), value: 'hourly' },
                { label: __('Twice a day'), value: 'twicedaily' },
                { label: __('Once a day'), value: 'daily' },
                { label: __('Off (only when I click Check now)'), value: 'off' }
              ]}
            />
          </Form.Item>

          <Form.Item
            className="mb-0 max-w-md"
            extra={__(
              '0 keeps everything forever. Unresolved critical findings are never deleted.'
            )}
            label={__('Keep history for (days)')}
            name="retention_days"
          >
            <InputNumber className="w-40" max={3650} min={0} />
          </Form.Item>
        </Card>
      )
    },
    {
      key: 'email',
      label: __('Email alerts'),
      children: (
        <Card>
          <Form.Item
            className="mb-5"
            label={__('Email me about changes')}
            name="email_enabled"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>

          <Form.Item
            className="mb-5 max-w-md"
            extra={__('Only changes at this severity or higher trigger an email.')}
            label={__('Alert severity')}
            name="email_threshold"
          >
            <Select
              disabled={isEmailFieldDisabled}
              options={[
                { label: __('Critical changes only'), value: 'critical' },
                { label: __('Critical and warnings'), value: 'warning' },
                { label: __('Everything, including info'), value: 'info' }
              ]}
            />
          </Form.Item>

          <Form.Item
            className="mb-0 max-w-md"
            extra={__('Leave empty to use the site admin email.')}
            label={__('Send alerts to')}
            name="email_recipient"
          >
            <Input
              disabled={isEmailFieldDisabled}
              placeholder={__('you@example.com')}
              type="email"
            />
          </Form.Item>
        </Card>
      )
    },
    // The report is generated by the pro add-on; without it the endpoints
    // behind Preview and Send now do not exist.
    ...(config.IS_PRO_EXIST
      ? [
          {
            key: 'report',
            label: __('Client report'),
            children: (
              <Card
                extra={
                  <Space>
                    <Button
                      disabled={isLoading}
                      loading={previewReport.isPending}
                      size="small"
                      onClick={preview}
                    >
                      {__('Preview')}
                    </Button>
                    <Button
                      disabled={isLoading}
                      loading={sendReport.isPending}
                      size="small"
                      onClick={sendNow}
                    >
                      {__('Send now')}
                    </Button>
                  </Space>
                }
                title={__('Weekly client report')}
              >
                <Form.Item
                  className="mb-5"
                  extra={__('Sent every Monday morning. Your branding, not ours.')}
                  label={__('Email a weekly summary')}
                  name="report_enabled"
                  valuePropName="checked"
                >
                  <Switch />
                </Form.Item>

                <Form.Item
                  className="mb-5 max-w-lg"
                  extra={__('Comma-separated. These addresses receive the report.')}
                  label={__('Send to')}
                  name="report_recipients"
                >
                  <Input placeholder={__('client@example.com, you@agency.com')} />
                </Form.Item>

                <div className="flex max-w-lg gap-3">
                  <Form.Item
                    className="mb-5 flex-1"
                    label={__('Your business name')}
                    name="report_brand_name"
                  >
                    <Input placeholder={__('Shown in place of the plugin name')} />
                  </Form.Item>
                  <Form.Item
                    className="mb-5 w-32"
                    label={__('Accent colour')}
                    name="report_brand_color"
                  >
                    <Input placeholder="#3b5bdb" />
                  </Form.Item>
                </div>

                <Form.Item
                  className="mb-5 max-w-lg"
                  label={__('Logo URL')}
                  name="report_logo_url"
                >
                  <Input placeholder="https://example.com/logo.png" />
                </Form.Item>

                <Form.Item
                  className="mb-0 max-w-lg"
                  extra={__('Replaces the default line at the bottom of the report.')}
                  label={__('Footer text')}
                  name="report_footer"
                >
                  <Input placeholder={__('Prepared by Your Agency')} />
                </Form.Item>
              </Card>
            )
          }
        ]
      : []),
    {
      key: 'ai',
      label: __('AI crawlers'),
      children: (
        <Card>
          <Form.Item
            className="mb-0"
            extra={__(
              'Notes the date each known AI crawler last visited. Full-page caching can hide some visits.'
            )}
            label={__('Record when AI crawlers visit')}
            name="bot_tracking"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>
        </Card>
      )
    }
  ]

  return (
    <>
      <PageHeader
        actions={
          <Tooltip title={__('Changes apply to the next scheduled check.')}>
            {/* Sits outside the Form element, so it is neither a submit button
                nor covered by the Form's disabled prop - both are wired by hand. */}
            <Button
              disabled={isLoading}
              loading={updateSettings.isPending}
              type="primary"
              onClick={() => form.submit()}
            >
              {__('Save settings')}
            </Button>
          </Tooltip>
        }
        title={__('Settings')}
      />

      <Form disabled={isLoading} form={form} layout="vertical" onFinish={submit}>
        <Tabs defaultActiveKey="checking" items={tabItems} />
      </Form>
    </>
  )
}
