// frontend/src/features/siteWide/SiteWidePage.vue
<script setup lang="ts">
import { Alert, Card, Table, Tag } from 'ant-design-vue'
import { useQuery } from '@tanstack/vue-query'
import { computed } from 'vue'
import { __ } from '@common/helpers/i18nWrap'
import { parseUtc } from '@common/helpers/datetime'
import call from '@/api/client'
import PageHeader from '@components/PageHeader.vue'
import When from '@components/When.vue'
import { palette } from '@config/theme'

interface BotRow {
  slug: string
  label: string
  user_agent: string
  last_seen: null | string
  hits: number
}

interface SitePanel {
  checked_at: null | string
  fields: Record<string, unknown>
  error: null | string
}

interface SiteStatus {
  robots: null | SitePanel
  sitemap: null | SitePanel
  settings: null | SitePanel
  bots: BotRow[]
  bot_tracking: boolean
  impaired: null | { since: string; reason: string }
}

const { data, isLoading } = useQuery({
  queryKey: ['site-status'],
  queryFn: () => call<SiteStatus>('status/site')
})

const robots = computed(() => data.value?.robots?.fields ?? {})
const sitemap = computed(() => data.value?.sitemap?.fields ?? {})
const settings = computed(() => data.value?.settings?.fields ?? {})
const aiBots = computed(() => (robots.value.ai_bots ?? {}) as Record<string, string>)
const isPublic = computed(() => settings.value.blog_public !== false)

const robotsRaw = computed(() => String(robots.value.raw ?? '').trim() || __('(empty file)'))
const sitemapUrl = computed(() => String(sitemap.value.url ?? ''))

// Borderless everywhere, to match the severity and status tags on the other
// screens; a bordered tag here read as a different control entirely.
const verdict = (slug: string) => {
  const value = aiBots.value[slug]

  if (value === 'blocked') return { color: 'error', label: __('Blocked') }
  if (value === 'allowed') return { color: 'success', label: __('Allowed') }

  return { color: undefined, label: __('Not specified') }
}

const staleness = (lastSeen: string) => {
  const seenAt = parseUtc(lastSeen)
  const daysAgo = seenAt ? (Date.now() - seenAt.getTime()) / 86_400_000 : 0

  return daysAgo > 30 ? palette.warning : palette.success
}

const columns = [
  { key: 'label', title: __('Crawler') },
  { key: 'slug', title: __('robots.txt says'), width: 170 },
  { key: 'last_seen', title: __('Last seen here'), width: 220 }
]
</script>

<template>
  <PageHeader :title="__('Site-wide')" />

  <!--
    Spacing lives on this column: margin utilities on antd roots lose to its
    cssinjs reset at high hash priority.
  -->
  <div class="flex flex-col gap-4">
    <Alert
      v-if="!isPublic"
      show-icon
      :description="
        __(
          'WordPress is asking search engines to stay away. Until this is turned off in Settings → Reading, your pages will not appear in search results.'
        )
      "
      :message="__('Search engines are being discouraged from indexing this site')"
      type="error"
    />

    <div class="grid grid-cols-1 items-start gap-4 lg:grid-cols-2">
      <Card :loading="isLoading" :title="__('robots.txt')">
        <p
          v-if="robots.reachable === false"
          class="m-0 py-6 text-center text-sm"
          :style="{ color: palette.inkMuted }"
        >
          {{ __('Not reachable.') }}
        </p>
        <div v-else class="flex flex-col gap-3">
          <Alert
            v-if="Boolean(robots.blocks_all)"
            show-icon
            :message="__('This file blocks all crawlers from the whole site.')"
            type="error"
          />
          <pre class="scm-code max-h-56">{{ robotsRaw }}</pre>
        </div>
      </Card>

      <Card :loading="isLoading" :title="__('XML sitemap')">
        <div v-if="sitemap.reachable" class="flex flex-col gap-2">
          <div class="flex items-baseline gap-2">
            <span class="text-3xl font-semibold leading-none">
              {{ Number(sitemap.url_count ?? 0) }}
            </span>
            <span class="text-sm" :style="{ color: palette.inkMuted }">
              {{ __('URLs listed') }}
            </span>
          </div>
          <a class="break-all text-xs" :href="sitemapUrl" rel="noreferrer" target="_blank">
            {{ sitemapUrl }}
          </a>
          <Alert
            v-if="sitemap.valid === false"
            show-icon
            :message="__('Sitemap is not valid XML.')"
            type="error"
          />
        </div>
        <p v-else class="m-0 py-6 text-center text-sm" :style="{ color: palette.inkMuted }">
          {{
            isPublic
              ? __('No sitemap found at the usual locations.')
              : __('WordPress disables the sitemap while search engines are discouraged.')
          }}
        </p>
      </Card>
    </div>

    <Card :body-style="{ padding: 0 }" :loading="isLoading" :title="__('AI crawlers')">
      <template #extra>
        <span class="text-xs" :style="{ color: palette.inkMuted }">
          {{ __('Last-seen counts only requests that reach WordPress. Caching can hide visits.') }}
        </span>
      </template>

      <Table :columns="columns" :data-source="data?.bots ?? []" :pagination="false" row-key="slug">
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'label'">
            <div class="flex flex-col">
              <span class="font-medium">{{ (record as BotRow).label }}</span>
              <span class="text-xs" :style="{ color: palette.inkFaint }">
                {{ (record as BotRow).user_agent }}
              </span>
            </div>
          </template>

          <template v-else-if="column.key === 'slug'">
            <Tag :bordered="false" :color="verdict((record as BotRow).slug).color">
              {{ verdict((record as BotRow).slug).label }}
            </Tag>
          </template>

          <template v-else-if="column.key === 'last_seen'">
            <span v-if="!data?.bot_tracking" class="text-xs" :style="{ color: palette.inkFaint }">
              {{ __('tracking off') }}
            </span>
            <span
              v-else-if="!(record as BotRow).last_seen"
              class="text-xs"
              :style="{ color: palette.inkFaint }"
            >
              {{ __('Never seen') }}
            </span>
            <span v-else class="flex items-center gap-2 text-sm">
              <span
                class="h-1.5 w-1.5 shrink-0 rounded-full"
                :style="{ background: staleness((record as BotRow).last_seen as string) }"
              />
              <When :value="(record as BotRow).last_seen" />
              <span class="text-xs" :style="{ color: palette.inkFaint }">
                {{ (record as BotRow).hits }}
              </span>
            </span>
          </template>
        </template>
      </Table>
    </Card>
  </div>
</template>

// frontend/src/features/siteWide/SiteWidePage.tsx
import { Alert, Card, Table, Tag } from 'antd'
import { useQuery } from '@tanstack/react-query'
import { __ } from '@common/helpers/i18nWrap'
import call from '@/api/client'
import { parseUtc } from '@common/helpers/datetime'
import PageHeader from '@components/PageHeader'
import When from '@components/When'
import { palette } from '@config/theme'

interface BotRow {
  slug: string
  label: string
  user_agent: string
  last_seen: null | string
  hits: number
}

interface SitePanel {
  checked_at: null | string
  fields: Record<string, unknown>
  error: null | string
}

interface SiteStatus {
  robots: null | SitePanel
  sitemap: null | SitePanel
  settings: null | SitePanel
  bots: BotRow[]
  bot_tracking: boolean
  impaired: null | { since: string; reason: string }
}

// Borderless everywhere, to match the severity and status tags on the other
// screens; a bordered tag here read as a different control entirely.
const verdictTag = (verdict?: string) => {
  if (verdict === 'blocked')
    return (
      <Tag bordered={false} color="error">
        {__('Blocked')}
      </Tag>
    )
  if (verdict === 'allowed')
    return (
      <Tag bordered={false} color="success">
        {__('Allowed')}
      </Tag>
    )

  return <Tag bordered={false}>{__('Not specified')}</Tag>
}

function Placeholder({ text }: { text: string }) {
  return (
    <p className="m-0 py-6 text-center text-sm" style={{ color: palette.inkMuted }}>
      {text}
    </p>
  )
}

export default function SiteWidePage() {
  const { data, isLoading } = useQuery({
    queryKey: ['site-status'],
    queryFn: () => call<SiteStatus>('status/site')
  })

  const robots = data?.robots?.fields ?? {}
  const sitemap = data?.sitemap?.fields ?? {}
  const settings = data?.settings?.fields ?? {}
  const aiBots = (robots.ai_bots ?? {}) as Record<string, string>
  const isPublic = settings.blog_public !== false

  return (
    <>
      <PageHeader title={__('Site Checks')} />

      {/* Spacing lives on this column: margin utilities on antd roots lose to
          its cssinjs reset at high hash priority. */}
      <div className="flex flex-col gap-4">
        {!isPublic && (
          <Alert
            showIcon
            description={__(
              'WordPress is asking search engines to stay away. Until this is turned off in Settings → Reading, your pages will not appear in search results.'
            )}
            message={__('Search engines are being discouraged from indexing this site')}
            type="error"
          />
        )}

        <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-2">
          <Card loading={isLoading} title={__('robots.txt')}>
            {robots.reachable === false ? (
              <Placeholder text={__('Not reachable.')} />
            ) : (
              <div className="flex flex-col gap-3">
                {Boolean(robots.blocks_all) && (
                  <Alert
                    showIcon
                    message={__('This file blocks all crawlers from the whole site.')}
                    type="error"
                  />
                )}
                <pre className="scm-code max-h-56">
                  {String(robots.raw ?? '').trim() || __('(empty file)')}
                </pre>
              </div>
            )}
          </Card>

          <Card loading={isLoading} title={__('XML sitemap')}>
            {sitemap.reachable ? (
              <div className="flex flex-col gap-2">
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-semibold leading-none">
                    {Number(sitemap.url_count ?? 0)}
                  </span>
                  <span className="text-sm" style={{ color: palette.inkMuted }}>
                    {__('URLs listed')}
                  </span>
                </div>
                <a
                  className="break-all text-xs"
                  href={String(sitemap.url ?? '')}
                  rel="noreferrer"
                  target="_blank"
                >
                  {String(sitemap.url ?? '')}
                </a>
                {sitemap.valid === false && (
                  <Alert showIcon message={__('Sitemap is not valid XML.')} type="error" />
                )}
              </div>
            ) : (
              <Placeholder
                text={
                  isPublic
                    ? __('No sitemap found at the usual locations.')
                    : __('WordPress disables the sitemap while search engines are discouraged.')
                }
              />
            )}
          </Card>
        </div>

        <Card
          extra={
            <span className="text-xs" style={{ color: palette.inkMuted }}>
              {__('Last-seen counts only requests that reach WordPress. Caching can hide visits.')}
            </span>
          }
          loading={isLoading}
          styles={{ body: { padding: 0 } }}
          title={__('AI crawlers')}
        >
          <Table<BotRow>
            dataSource={data?.bots ?? []}
            pagination={false}
            rowKey="slug"
            columns={[
              {
                title: __('Crawler'),
                dataIndex: 'label',
                render: (label: string, row) => (
                  <div className="flex flex-col">
                    <span className="font-medium">{label}</span>
                    <span className="text-xs" style={{ color: palette.inkFaint }}>
                      {row.user_agent}
                    </span>
                  </div>
                )
              },
              {
                title: __('robots.txt says'),
                dataIndex: 'slug',
                width: 170,
                render: (slug: string) => verdictTag(aiBots[slug])
              },
              {
                title: __('Last seen here'),
                dataIndex: 'last_seen',
                width: 220,
                render: (lastSeen: null | string, row) => {
                  if (!data?.bot_tracking) {
                    return (
                      <span className="text-xs" style={{ color: palette.inkFaint }}>
                        {__('tracking off')}
                      </span>
                    )
                  }

                  if (!lastSeen) {
                    return (
                      <span className="text-xs" style={{ color: palette.inkFaint }}>
                        {__('Never seen')}
                      </span>
                    )
                  }

                  const seenAt = parseUtc(lastSeen)
                  const daysAgo = seenAt ? (Date.now() - seenAt.getTime()) / 86_400_000 : 0

                  return (
                    <span className="flex items-center gap-2 text-sm">
                      <span
                        className="h-1.5 w-1.5 shrink-0 rounded-full"
                        style={{ background: daysAgo > 30 ? palette.warning : palette.success }}
                      />
                      <When value={lastSeen} />
                      <span className="text-xs" style={{ color: palette.inkFaint }}>
                        {row.hits}
                      </span>
                    </span>
                  )
                }
              }
            ]}
          />
        </Card>
      </div>
    </>
  )
}
