// frontend/src/features/flightLog/FlightLogPage.vue
<script setup lang="ts">
import { Button, Card, Select, Table, Tag } from 'ant-design-vue'
import { computed, ref } from 'vue'
import { __, sprintf } from '@common/helpers/i18nWrap'
import { useFindings, useTargets } from '@/api/queries'
import { changeLabel } from '@components/changeLabels'
import PageHeader from '@components/PageHeader.vue'
import SeverityTag from '@components/SeverityTag.vue'
import When from '@components/When.vue'
import { palette } from '@config/theme'
import { useFlightLogStore } from '@/store/flightLogStore'
import FindingDrawer from './FindingDrawer.vue'
import type { Finding, FindingStatus } from '@/api/types'

const STATUS_LABELS: Record<FindingStatus, string> = {
  open: __('Open'),
  resolved: __('Resolved'),
  auto_resolved: __('Auto-resolved'),
  muted: __('Muted')
}

const store = useFlightLogStore()
const selected = ref<Finding | null>(null)

// The store's `filters` is a computed, so vue-query refetches on every change.
const { data, isLoading } = useFindings(store.filters)
const { data: targets } = useTargets()

const total = computed(() => data.value?.total ?? 0)
const rows = computed(() => data.value?.items ?? [])

const severityOptions = [
  { label: __('Critical'), value: 'critical' },
  { label: __('Warning'), value: 'warning' },
  { label: __('Info'), value: 'info' }
]

const statusOptions = (Object.keys(STATUS_LABELS) as FindingStatus[]).map(status => ({
  label: STATUS_LABELS[status],
  value: status
}))

const targetOptions = computed(() =>
  (targets.value ?? []).map(target => ({ label: target.label, value: target.id }))
)

const columns = [
  { key: 'severity', title: __('Severity'), width: 120 },
  { key: 'change_type', title: __('What changed') },
  { key: 'target_label', title: __('Page'), width: 180 },
  { key: 'status', title: __('Status'), width: 140 },
  { key: 'created_at', title: __('Detected'), width: 140 }
]

const pagination = computed(() => ({
  current: data.value?.page ?? 1,
  pageSize: data.value?.per_page ?? 20,
  total: total.value,
  showSizeChanger: false,
  // Kept on a single page too: it gives the table a footer and says how much
  // is on screen, which the bare table did not.
  hideOnSinglePage: false,
  showTotal: (count: number, range: [number, number]) =>
    sprintf(__('%d-%d of %d'), range[0], range[1], count)
}))

const countLabel = computed(() =>
  total.value === 1 ? __('1 change') : sprintf(__('%d changes'), total.value)
)
</script>

<template>
  <PageHeader :title="__('Flight Log')" />

  <!--
    Filters live inside the results card rather than floating above it: they
    act on the table below, so they read as one surface with it and share its
    left edge.
  -->
  <Card :body-style="{ padding: 0 }">
    <div
      class="flex flex-wrap items-center gap-2 border-0 border-b border-solid px-4 py-3"
      :style="{ borderColor: palette.lineSoft }"
    >
      <Select
        allow-clear
        class="w-full sm:w-52"
        max-tag-count="responsive"
        mode="multiple"
        :options="severityOptions"
        :placeholder="__('All severities')"
        :value="store.severity"
        @change="value => store.setSeverity(value as never)"
      />
      <Select
        allow-clear
        class="w-full sm:w-52"
        max-tag-count="responsive"
        mode="multiple"
        :options="statusOptions"
        :placeholder="__('Any status')"
        :value="store.status"
        @change="value => store.setStatus(value as never)"
      />
      <Select
        allow-clear
        class="w-full sm:w-52"
        :options="targetOptions"
        :placeholder="__('All pages')"
        :value="store.targetId"
        @change="value => store.setTargetId(value as number | undefined)"
      />

      <!--
        Default size, not small: it sits in a row with the Selects and has to
        share their control height.
      -->
      <Button v-if="store.hasFilters" @click="store.reset()">{{ __('Clear filters') }}</Button>

      <span class="ml-auto pr-1 text-xs tabular-nums" :style="{ color: palette.inkMuted }">
        {{ countLabel }}
      </span>
    </div>

    <Table
      :columns="columns"
      :custom-row="record => ({ onClick: () => (selected = record as Finding) })"
      :data-source="rows"
      :loading="isLoading"
      row-class-name="cursor-pointer"
      row-key="id"
      :pagination="pagination"
      @change="info => store.setPage(info.current ?? 1)"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'severity'">
          <SeverityTag :severity="(record as Finding).severity" />
        </template>

        <template v-else-if="column.key === 'change_type'">
          <div class="flex min-w-0 flex-col">
            <span class="font-medium">{{ changeLabel((record as Finding).change_type) }}</span>
            <span class="truncate text-xs" :style="{ color: palette.inkMuted }">
              {{ (record as Finding).explanation.what }}
            </span>
          </div>
        </template>

        <template v-else-if="column.key === 'target_label'">
          {{ (record as Finding).target_label ?? __('Site-wide') }}
        </template>

        <template v-else-if="column.key === 'status'">
          <Tag
            :bordered="false"
            :color="(record as Finding).status === 'open' ? 'default' : 'success'"
          >
            {{ STATUS_LABELS[(record as Finding).status] }}
          </Tag>
        </template>

        <template v-else-if="column.key === 'created_at'">
          <When :value="(record as Finding).created_at" />
        </template>
      </template>

      <template #emptyText>
        <div class="py-10 text-center">
          <p class="m-0 text-sm font-medium" :style="{ color: palette.ink }">
            {{ __('No changes recorded yet.') }}
          </p>
          <p class="m-0 text-xs" :style="{ color: palette.inkMuted }">
            {{ __('Anything that changes on your monitored pages will appear here.') }}
          </p>
        </div>
      </template>
    </Table>
  </Card>

  <FindingDrawer :finding="selected" @close="selected = null" />
</template>

// frontend/src/features/flightLog/FlightLogPage.tsx
import { Button, Card, Select, Table, Tag } from 'antd'
import { useMemo, useState } from 'react'
import { __, sprintf } from '@common/helpers/i18nWrap'
import { useFindings, useTargets } from '@/api/queries'
import { changeLabel } from '@components/changeLabels'
import PageHeader from '@components/PageHeader'
import SeverityTag from '@components/SeverityTag'
import When from '@components/When'
import { palette } from '@config/theme'
import { selectFilters, useFlightLogStore } from '@/store/flightLogStore'
import FindingDrawer from './FindingDrawer'
import type { Finding, FindingStatus, Severity } from '@/api/types'

const STATUS_LABELS: Record<FindingStatus, string> = {
  open: __('Open'),
  resolved: __('Resolved'),
  auto_resolved: __('Auto-resolved'),
  muted: __('Muted')
}

export default function FlightLogPage() {
  const [selected, setSelected] = useState<Finding | null>(null)
  const store = useFlightLogStore()
  // Derived here rather than in a store selector: selectFilters builds a new
  // object every call, which would re-render forever as a zustand selector.
  const filters = useMemo(() => selectFilters(store), [store])

  const { data, isLoading } = useFindings(filters)
  const { data: targets } = useTargets()

  const hasFilters =
    store.severity.length > 0 || store.targetId !== undefined || store.status.length !== 1
  const total = data?.total ?? 0

  return (
    <>
      <PageHeader title={__('Change History')} />

      {/* Filters live inside the results card rather than floating above it:
          they act on the table below, so they read as one surface with it and
          share its left edge. */}
      <Card styles={{ body: { padding: 0 } }}>
        <div
          className="flex flex-wrap items-center gap-2 border-0 border-b border-solid px-4 py-3"
          style={{ borderColor: palette.lineSoft }}
        >
          <Select<Severity[]>
            allowClear
            className="w-full sm:w-52"
            maxTagCount="responsive"
            mode="multiple"
            placeholder={__('All severities')}
            value={store.severity}
            onChange={store.setSeverity}
            options={[
              { label: __('Critical'), value: 'critical' },
              { label: __('Warning'), value: 'warning' },
              { label: __('Info'), value: 'info' }
            ]}
          />
          <Select<FindingStatus[]>
            allowClear
            className="w-full sm:w-52"
            maxTagCount="responsive"
            mode="multiple"
            placeholder={__('Any status')}
            value={store.status}
            onChange={store.setStatus}
            options={(Object.keys(STATUS_LABELS) as FindingStatus[]).map(status => ({
              label: STATUS_LABELS[status],
              value: status
            }))}
          />
          <Select
            allowClear
            className="w-full sm:w-52"
            placeholder={__('All pages')}
            value={store.targetId}
            onChange={store.setTargetId}
            options={(targets ?? []).map(target => ({ label: target.label, value: target.id }))}
          />
          {/* Default size, not small: it sits in a row with the Selects and has
              to share their control height. */}
          {hasFilters && <Button onClick={store.reset}>{__('Clear filters')}</Button>}

          <span className="ml-auto pr-1 text-xs tabular-nums" style={{ color: palette.inkMuted }}>
            {total === 1 ? __('1 change') : sprintf(__('%d changes'), total)}
          </span>
        </div>

        <Table<Finding>
          dataSource={data?.items ?? []}
          loading={isLoading}
          rowClassName="cursor-pointer"
          rowKey="id"
          onRow={finding => ({ onClick: () => setSelected(finding) })}
          locale={{
            emptyText: (
              <div className="py-10 text-center">
                <p className="m-0 text-sm font-medium" style={{ color: palette.ink }}>
                  {__('No changes recorded yet.')}
                </p>
                <p className="m-0 text-xs" style={{ color: palette.inkMuted }}>
                  {__('Anything that changes on your monitored pages will appear here.')}
                </p>
              </div>
            )
          }}
          pagination={{
            current: data?.page ?? 1,
            pageSize: data?.per_page ?? 20,
            total: data?.total ?? 0,
            showSizeChanger: false,
            // Kept on a single page too: it gives the table a footer and says
            // how much is on screen, which the bare table did not.
            hideOnSinglePage: false,
            showTotal: (count, range) => sprintf(__('%d-%d of %d'), range[0], range[1], count),
            onChange: store.setPage
          }}
          columns={[
            {
              title: __('Severity'),
              dataIndex: 'severity',
              width: 120,
              render: (severity: Severity) => <SeverityTag severity={severity} />
            },
            {
              title: __('What changed'),
              dataIndex: 'change_type',
              render: (type: string, finding) => (
                <div className="flex min-w-0 flex-col">
                  <span className="font-medium">{changeLabel(type)}</span>
                  <span className="truncate text-xs" style={{ color: palette.inkMuted }}>
                    {finding.explanation.what}
                  </span>
                </div>
              )
            },
            {
              title: __('Page'),
              dataIndex: 'target_label',
              width: 180,
              render: (label: null | string) => label ?? __('Site-wide')
            },
            {
              title: __('Status'),
              dataIndex: 'status',
              width: 140,
              render: (status: FindingStatus) => (
                <Tag bordered={false} color={status === 'open' ? 'default' : 'success'}>
                  {STATUS_LABELS[status]}
                </Tag>
              )
            },
            {
              title: __('Detected'),
              dataIndex: 'created_at',
              width: 140,
              render: (at: null | string) => <When value={at} />
            }
          ]}
        />
      </Card>

      <FindingDrawer finding={selected} onClose={() => setSelected(null)} />
    </>
  )
}
